[workspace]
resolver = "2"

members = [
    "crates/tglib",
    "crates/tglib-core",
    "crates/tglib-client",
    "crates/tglib-tdlib",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["igornet0"]
repository = "https://github.com/igornet0/tglib"
description = "Telegram User API library (TDLib) for Rust"

[workspace.dependencies]
tokio = { version = "1.47", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "v7", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
tracing = "0.1"
toml = "0.8"
dashmap = "6"
parking_lot = "0.12"
async-trait = "0.1"

tglib = { path = "crates/tglib" }
tglib-core = { path = "crates/tglib-core" }
tglib-client = { path = "crates/tglib-client" }
tglib-tdlib = { path = "crates/tglib-tdlib" }

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"
